import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import { MyContext, InternalConsumer } from 'context-proj';
import type { MyContextType } from 'context-proj';
import { MyConsumer1 } from 'context-consumer1';
import { MyConsumer2 } from 'context-consumer2';


export default function Home(): JSX.Element {
  const myContext: MyContextType = {
    someFunction: () => 12,
    someString: 'I changed it!',
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <MyContext.Provider value={myContext}>
            <InternalConsumer />
            <MyConsumer1 />
            <MyConsumer2 />
          </MyContext.Provider>
        </div>
      </main>
    </div>
  );
}
